### ISSUE TITLE
Unable to access Todos inside Container build

### ISSUE THREAD

**Issue by vhscom** [aprakasa/sveltekit-node-docker#3]
Thanks for the video and example code. Unfortunately, I'm unable to browse Todos after building and running the container following the steps in the readme. Here's what happens when I try to view Todos:

<img width="1313" alt="Screen Shot 2022-10-12 at 12 41 30 PM" src="https://user-images.githubusercontent.com/97140109/195400775-0d2574e9-79ca-40a7-8063-f72eb1ab118e.png">

**Comment by aprakasa** [comment]
Because of the breaking changes https://github.com/sveltejs/kit/pull/6510
Basically need to set the [ORIGIN ](https://github.com/sveltejs/kit/tree/master/packages/adapter-node#origin-protocol_header-and-host_header)environment variable 
I add an example from my latest commit.

**Comment by vhscom** [comment]
Good to know. Thank you. 🙏
